### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by adamltyson**

### CODE REVIEW

**Comment by FedeClaudi** [comment]
Cheers

**Comment by adamltyson** [comment]
For now, yeah. I'll make a BG-wide one that could take over later if you wanted.

**Comment by adamltyson** [comment]
Up to you if you want to merge this one, with your email address in. The default BG one comes up on the panel on the right hand side now.

**Comment by FedeClaudi** [comment]
okay, let's leave the default BG one then so that there's one fewer thing to keep updating.

**Pull request closed without merging**
