### PR TITLE
Pin vtk

### PR DESCRIPTION
**Pull request by IgorTatarnikov**
Pin vtk version to fix Windows CI tests

### CODE REVIEW

**Comment by IgorTatarnikov** [comment]
Pinning `vtk` fixed the Windows test failing on CI. However, currently http://api.brain-map.org/api/v2 is down causing the gene expression smoke tests to fail.

**Comment by alessandrofelder** [comment]
Should we merge this given the failures are unrelated to the VTK problem?

**Comment by IgorTatarnikov** [comment]
Seems the problems at [http://api.brain-map.org/api/v2](http://api.brain-map.org/api/v2) have resolved

**Review by adamltyson — APPROVED** [review]

**Comment by adamltyson** [comment]
Thanks @IgorTatarnikov. I've raised https://github.com/brainglobe/brainrender/issues/399 to revert this at some point.

**Pull request merged**
