### PR TITLE
Hetamap visualization

### PR DESCRIPTION
**Pull request by FedeClaudi**
Added code to create heatmaps visualizations.

The idea is that, starting from a dictionary that maps `region names` -> `scalar values` brainrender adds all the regions to a `Scene`, colors them according to the scalar value and a colormap and then visualizes things. This way the regions colors are a `heatmap`.

For the visualization, the `Scene` is 'sliced' with two `Plane` objects to create an almost 2D visual feel (though of course the whole thing is rendered in 3D with `vedo`). The use can select different orientations ('frontal', 'top', 'sagittal') which specifies the orientation of the planes slicing the scene and of the camera, and specify the position of the 'slice' (along an axis that depends on the orientation) and the thickness of the slice (distance between planes).

image

image

### CODE REVIEW

**Review by adamltyson — APPROVED** [review]

**Comment by FedeClaudi** [comment]
@vigji let me know if you have time to give this a quick look!

**Comment by FedeClaudi** [comment]
Hey, thanks for having a look.

> It is not entirely clear to me here why is there a requirement for two planes, the use cases that I can mostly think of would require an actual 2D slice no?

You need two planes to cut through to get a 2D slice. It's like doing histology, you cut the brain twice to get a single slice which you then use for imaging. Similarly, a single plane here cut's the brain in half so you're left with still a lot of 3D geometry. You need a second cut to get rid of it. (They way it works in `vedo`, when you cut with a plane all the geometry on one side of the plane is destroyed but the other side remains intact).
You could cut twice with the same plane, the first time removing what's on one side of the plane and the second time what's on the other side of the plane, but then instead of being left with a 2D slice you're left with nothing. That's why I offset the second plane slightly (like in histology, you can't do a 0um thick slice). Then you're left with something that is close to a 2D image but still has some thickness. 
I know this looks different from e.g. what you'd do in matplotlib, but I kind of like the way it looks when you still have a bit of depth to it.
You can always make the spacing between the planes very small.



For the second point, I can for sure pass the coordinates of the plane, but I'm not sure what you mean exactly? The `(x,y)` coordinates of the regions' meshes' contours in the slicing plane? How would you use these to fill them up, and why would that be preferable?

**Comment by vigji** [comment]
> You need two planes to cut through to get a 2D slice. [...] You can always make the spacing between the planes very small.

Now I see the point! I thought that you were somehow projecting the intersection on the slice, not cutting 3D volumes in 3D space. Maybe it would be good to have as the default the minimum value possible, and increase the thickness if you want the "slicing" feeling? I think this would be more intuitive to me!

 
> For the second point, I can for sure pass the coordinates of the plane, but I'm not sure what you mean exactly? The `(x,y)` coordinates of the regions' meshes' contours in the slicing plane? How would you use these to fill them up, and why would that be preferable?

I can imagine having the coordinates in the 2D reference frame of the slice, and then use them in a separate plot. The reasons for me to want that could be:
 - finer control over shape appearance (I know there's a lot of customisability also in vedo, but I feel that the matplitlib fill is, if less nice maybe, entirely deterministic - see eg the thickness of the contour lines in the images of your examples), or, if not finer, just with an API I'm more familiar with parameter-wise
 - integration with other plots, to show the section in an insert or a subplot in a bigger panel with no illustrator work
 - importantly, saving it as vector format (pdf or svg), if I remember correctly this is not an option vedo offers ATM

**Comment by FedeClaudi** [comment]
I see, good point.

I need to think about how to do it. Vedo has some code to get the intersection of two meshes, so that might work.
Well, that gives you the 3D coordinates of where the intersection is in atlas space, then I guess we need a bit of linear algebra to project them onto the plane. I'll give it a shot I thin it would be cool to have!

**Comment by vigji** [comment]
Ok, I was thinking that maybe would come out of the box from vedo's functions!

If there's lot of algebra involved, maybe it's wiser to put that effort in a different PR :D 

Also, if the intercept calculation can be done using a different mesh slicer (I don't know what mesh libraries might offer that), if you have to invest in the linear algebra for the projection it could even be a separate repo without the requirement of the `vedo` backend!

**Comment by marcomusy** [comment]
if it helps you can cut triangular meshes easily in `vedo` eg.
```python
from vedo import *
s=Sphere().wireframe()
p=Grid().scale(3).triangulate()
sp=s.intersectWith(p)
print(sp.points().shape)
show(s,p, sp, axes=1)
```

Screenshot 2022-01-17 at 12 06 41

also projecting anything on any plane is also out of the box - check out:
```
examples/basic/silhouette1.py
examples/basic/silhouette2.py
```

**Comment by FedeClaudi** [comment]
Awesome, `vedo` always has a solution! Seems like it should be relatively easy to do @vigji !

**Comment by marcomusy** [comment]
PS: reading better maybe projecting is **not** what you're after... 

- if you want to _rotate_ the plane to make it conicide with the xy plane the follow discussion https://github.com/marcomusy/vedo/issues/561#issuecomment-996908553
- to fill a closed contour in the xy plane you can use `triangulate()`.

**Comment by FedeClaudi** [comment]
I think what we need is: given a plane with any orientation and an additional mesh -> get the coordinates of the intersection between the two and project them onto the plane such that in the end you're left with a set of 2D coordinates which represent the location of intersections between the mesh and plane in the plane's own coordinates system. 

So I think cutting + projection or intersection + projection should do it.

**Comment by marcomusy** [comment]
> a set of 2D coordinates which represent the location of intersections between the mesh and plane in the plane's own coordinates system.

cutting a sphere with a plane always gives a circle, but projecting a circle on a plane (almost) always gives an ellipse.... but you want the circle not the ellipse :)

```python
from vedo import *
s=Sphere().wireframe()
p=Grid().scale(3).triangulate().rotateX(20).rotateY(20).z(.1)
sp=s.intersectWith(p).lw(8)
plane = Plane(pos=(2,0,2), normal=(1,0,1), sx=5).alpha(0.1)
so = sp.clone().projectOnPlane(plane).c('k').alpha(1)
show(s,p,sp,so,plane, axes=1)
```
Screenshot 2022-01-18 at 11 49 58

So do not use `projectOnPlane`.
As you can see from the link above the linear algebra involved is trivial, simply use `applyTransform(T)` where matrix `T=np.array([v0,v1,v2])`, `v2=np.cross(v0,v1)` .

**Comment by FedeClaudi** [comment]
Oh it seems like I was mistaken about `plane.points()`, it does give the vertices of the plane which I can use to get the vectors I need. This works:

```python
    pts = plane.points() - plane.points()[0]
    v = pts[1] / np.linalg.norm(pts[1])
    w = pts[2] / np.linalg.norm(pts[2])

    M = np.vstack([v, w]).T  # 3 x 2

    projected = {}
    for n, actor in enumerate(regions_actors):
        # get region/plane intersection points
        intersection = plane.intersectWith(actor._mesh).points() # points: (N x 3)
        projected[actor.name] = intersection @ M

    return projected
```

but I can't control the orientation of the vectors. E.g. this image is upside down compared to how it should look like:

image

**Comment by FedeClaudi** [comment]
Btw, @marcomusy  what's the easiest way to get a camera that faces an arbitrary plane (i.e. it's orthogonal to it)?

@vigji  is the output above what you had in mind? Can you share code on how to use it to make nice plots in matplotlib?

**Comment by marcomusy** [comment]
i guess it depends on how you send [u,w] to [(0,1),(1,0)], flipping them should flip the image.

**Comment by marcomusy** [comment]
> Btw, @marcomusy what's the easiest way to get a camera that faces an arbitrary plane (i.e. it's orthogonal to it)?

you need to prescribe `camera=dict(pos=(....), focalPoint=(....))`

**Comment by vigji** [comment]
> @vigji is the output above what you had in mind? Can you share code on how to use it to make nice plots in matplotlib?

I don't have anything particularly fancy, I just use plt.fill(contour_x, contour_y) to outline the brains in my plot, or with a facecolor color-coding for different regions!

**Comment by FedeClaudi** [comment]
Mmm, I'm not sure that this will work:

image

It seems that it expects the points to be in order, and I guess separate sets of points for the left/right halves of each region... 

I'm happy to have it export the coordinates, but I'm not sure of how much use it would be unless we come up with a way to sort the points?

**Comment by vigji** [comment]
:D I love this abstract art!

Absolutely, that is essential, never consider it as I was getting the points in order with the slicing function I was using...maybe there's a quick way of sorting the points by euclidean distance to each other?

**Comment by FedeClaudi** [comment]
Lol.

I think sorting could work, an alternative is fitting a piecewise linear curve to the points (or a spline). I actually have some Julia code for this so it would be easy enough to implement. The only difficulty is in dealing with meshes that are separate (e.g., the two halves between L/R hemispheres).



I'm starting to think that this might become something a bit too involved to be contained within brainrender. It might be best to have it as a small separate package? I see it as:

1. use brainrender/vedo to slice atlas/regions with a plane at arbitrary orientation
2. get the coordinates of each meshes' slice for post hoc analysis
3. either use brainrender to create a visualization or a matplotlib one, with nicely defined presets etc.

This way also brainrender wouldn't have matplotlib as a dependency and it wouldn't have to include the code for sorting/cleaning these points stuff.

**Comment by vigji** [comment]
Yes, I agree!

**Comment by FedeClaudi** [comment]
Okay, moved development to: https://github.com/brainglobe/bg-heatmaps

**Comment by marcomusy** [comment]
Probably adding .join(reset-True) to line helps in ordering the points.

**Comment by FedeClaudi** [comment]
At the cost of sounding repetitive:
> Awesome, vedo always has a solution! 

The trick was to split the plane/mesh intersection by connectivity and then do the `join` operation.
@marcomusy  `vedo` is truly an amazing library, it's really incredible the ammount of work you've put into it.
I really hope you'll get all the credit you deserve for it!

```python
    for n, actor in enumerate(regions_actors):
        # get region/plane intersection
        intersection = plane.intersectWith(
            actor._mesh.triangulate()
        )  # points: (N x 3)

        if not intersection.points().shape[0]:
            continue  # no intersection

        pieces = intersection.splitByConnectivity()
        for piece_n, piece in enumerate(pieces):

            # sort coordinates
            points = piece.join(reset=True).points()

            projected[actor.name + f'_segment_{piece_n}'] = points @ M
```

image


@vigji  we're almost there! I just need to clean up the code a bit so that the users can customize the renders/plots appearance. With the plot being upside down I'm not sure what we can do since what is 'up' will depend on the atlas orientation, how the cutting planes were defined etc... I guess maybe we can provide pre-defined transformations e.g. to rotate all coordinates by an angle, or mirror across one axis etc...

**Comment by marcomusy** [comment]
> With the plot being upside down I'm not sure what we can do 

What if you change to:
`w = -pts[2] / np.linalg.norm(pts[2])`

**Comment by vigji** [comment]
This is amazing! Great job with the library @marcomusy :)

What I was thinking about though is just a function for the user to get the coordinates though! You can have a tutorial on how to use it, but I don't think that the matplotlib plotting part should be handled by you, there you enter the domain of something most users will be very familiar with and will want to customise by themselves in any way.

**Comment by vigji** [comment]
> @vigji we're almost there! I just need to clean up the code a bit so that the users can customize the renders/plots appearance. With the plot being upside down I'm not sure what we can do since what is 'up' will depend on the atlas orientation, how the cutting planes were defined etc... I guess maybe we can provide pre-defined transformations e.g. to rotate all coordinates by an angle, or mirror across one axis etc...

I think we just need to ensure a consistent behavior for the 3 standard views, and a reasonable interface for the user to specify a custom new slicing.

Maybe passing min n=3 3D coordinates that get interpolated to define the edges of the slicing plane? Then the user can reorient it in full and fix the potential upside-down projection themselves just by inverting the order of the points.

I'm thinking about the coordinates as to me they are a good way for a user to represent of the plane cutting the volume. Specifying manually angles and offsets I think would produce endless tinkering and adjustment for the slicing plane to cut through the regions you are interested. With coordinated you get very fine control over where the plane is cutting

**Comment by FedeClaudi** [comment]
@marcomusy  that works, brilliant!

Btw, are you on twitter? I'd like to give you a shoutout for all the help when this is released

**Comment by marcomusy** [comment]
I do not have twitter... maybe I should :)

**Comment by FedeClaudi** [comment]
You should! I'll still thank you and vedo for being awesome ;)

**Pull request merged**
