### PR TITLE
Docstring changes and some suggestions

### PR DESCRIPTION
**Pull request by seankmartin**
Hi, 

Amazing repository, delighted to see such an easy-to-use renderer for neuroscience.

I have been using this quite a lot recently, and have a few suggested edits if you are interested in them.
I'm open to any thoughts and further edits on these of course!

Best wishes,
Sean

### CODE REVIEW

**Comment by FedeClaudi** [comment]
Hi, 

Thanks!

The comments look really good (so many typos haha), thank you so much for sending this in.  The `screenshot.py` example is also very useful. 

The only thing I'm not sure is `settings.RICH_TRACEBACK` to disable the formatting of error messages. Is there any reason why you'd like to switch those off?

**Comment by seankmartin** [comment]
Great, glad to hear it!

The settings.RICH_TRACKBACK is because I am using brainrender along with another application where I have many GB of local variables.
So if a crash happens during runtime (which it often does because I write dumb code haha) then the rich traceback tries to display all the local variables to terminal, which it can't do because there are too many (well it probably could do it, but it would take a very long time).
This causes the program to hang and needs manual killing.
Plus it is very hard to find the cause of the bug without running again in debug mode.

So I suggested the ability to suppress the high detail traceback in case any others run into a similar issue!
Though perhaps there is another better solution to suppressing the local variables if they are very big?
If it seems too niche that's no worries at all, I'll just keep it on my local branch

**Comment by FedeClaudi** [comment]
I see, makes sense. So `pyinspect` renders errors similar to the way `rich` does (and it uses rich).  It has [an option](https://github.com/FedeClaudi/pyinspect/blob/02b9661eb90e75e55586b2627f79f2868276bee6/pyinspect/exceptions.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L103) to show/hide locals in the error trace or even to decide how many levels of locals to show in the stack. 

I think the best option would be to have `show_locals = settings.DEBUG`, this way it will generally not show them unless the users starts brainrender in debug mode, in which case it might want to have that extra information. 
This way we avoid adding an additional settings that users might be confused about. 

Btw, in general I think that if after importing brainrender in your code you use `install_traceback` with the parameter you need it will override brainrender's.

**Comment by seankmartin** [comment]
Yeah, that sounds perfect, I think what you suggest makes much more sense.

Also glad to hear about the ability to override the `show_locals` parameter if call `install_traceback` again, that would be great for me, so I'll definitely try that out too - thanks!

**Comment by FedeClaudi** [comment]
Awesome. 

If you want to add a commit with the suggested `settings.DEBUG` change I'd be very happy to merge.

**Comment by seankmartin** [comment]
Ok added that, hopefully what you had in mind, but please let me know if not.
Also realised that I was missing a closing newline in the screenshot example file, so added that as well.

**Comment by FedeClaudi** [comment]
Looks good. Thanks for the PR!

**Pull request merged**
